kind = "api"
previewPath = "/discord-bot"
title = "Discord Bot"

[[services]]
localPort = 3000
name = "Discord Bot"
paths = ["/discord-bot"]

[services.development]
run = "pnpm --filter @workspace/discord-bot run start"

[services.production]

[services.production.run]
args = ["pnpm", "--filter", "@workspace/discord-bot", "run", "start"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"

[services.production.health.startup]
path = "/discord-bot"
