name: Repo Relay

on:
  push:
  pull_request:
  issues:
  release:

jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Relay
        uses: repo-relay/action-discord@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
